### ISSUE TITLE
Tabs disproportionally small for <1280px windows

### ISSUE THREAD

**Issue by adambuczynski** [atom/one-dark-ui#134] opened 2016-05-27 20:15 UTC
I find that the tabs have become disproportionally small for smaller windows, even though there is plenty of space left for them to grow. This makes it hard to read what the filename is, because the close dot appears over the file name:

![image](https://cloud.githubusercontent.com/assets/490562/15620048/06ace806-24ac-11e6-9d90-1c90acc2a5d3.png)

Widening the window fixes the issue:

![image](https://cloud.githubusercontent.com/assets/490562/15620058/132cc916-24ac-11e6-931a-f8de7c951da6.png)

The breakpoint seems to be at 1280px window size.

This is with Atom 1.9.0-dev-5eb0a03 on OS X 10.11.5.

**Comment by 50Wliu** [comment] 2016-05-27 20:17
You can change whether the tab width is as small as it can be or spacious in the UI settings (called Tab Sizing).  The default is auto, which adjusts the tab size based on your window size.

**Comment by adambuczynski** [comment] 2016-05-27 20:25
@50Wliu I don't think that's the problem. I am aware of that setting, but it used to be much more sensible width. If you look at the screenshot you can see that there is way too much space left for the tabs to warrant them being that small. I think it should be tweaked a bit. 

It used to be fine in previous versions of Atom.

**Comment by adambuczynski** [comment] 2016-05-28 00:23
@50Wliu I think simply changing the breakpoint for auto mode to switch from even to minimum to maybe 800px or even 1024px instead of 1280px would be sufficient to address this.

The problem with this "smart" auto behaviour, is that ideally, it should take into account how many tabs are open, and realize that if there's 1200px of space, yet only 3 tabs are open, it can give them generous space and not revert to minimum.

Another option to improve this would be to increase the minimum size a bit, and do something about the dot blocking the filename.

**Comment by 50Wliu** [comment] 2016-05-28 00:43
@simurai

**Comment by simurai** [comment] 2016-05-28 00:55
Yeah, it's not that "smart". The rule for `Tab Sizing: Miniumum` (Auto for small windows) is:

1. Make the tab only as wide as needed.
2. If the file name is very long, cut it off at some point.

![screen shot 2016-05-28 at 9 48 23 am](https://cloud.githubusercontent.com/assets/378023/15624066/58d4e680-24b9-11e6-84c4-c61f6a100a6a.png)

To improve that it would need to be resized with JS.

Or maybe another option: "Take up as much space as possible". That would be like the tabs on OS X (terminal, finder etc.)

**Comment by adambuczynski** [comment] 2016-05-28 01:12
I find that "take up as much space as possible up to a certain max width" as Chrome does works quite well. What's also nice, is that the text gets faded towards the end so the close button doesn't overlap the text:

![image](https://cloud.githubusercontent.com/assets/490562/15624191/61c6312e-24d5-11e6-88db-f0886b72dd8a.png)

As you can see it's a bit less graceful in the Atom theme:

![image](https://cloud.githubusercontent.com/assets/490562/15624205/adbc5b3a-24d5-11e6-840a-26694826da31.png)

Seems the "minimum" setting does make the tabs wider depending on content, but it doesn't take into account that the `x` for closing the tab also needs to fit, and it's poorly visible when it overlaps the filename.

**Comment by simurai** [comment] 2016-05-28 04:14
Have yo tried switching to `Tab Sizing: Even`? It's pretty close to Chrome's behavior.

![screen shot 2016-05-28 at 12 53 12 pm](https://cloud.githubusercontent.com/assets/378023/15625024/6fd52862-24d3-11e6-9c8d-1ac2d633a69a.png)

![tabs](https://cloud.githubusercontent.com/assets/378023/15625025/7ab1303c-24d3-11e6-88b1-85a3b72045bb.gif)

> Added bonus of Chrome behaviour is that if you close a tab, the other tabs actually move/resize in such a manner initially, that the close button of the next tab will be exactly under your mouse cursor.

Yeah, that would be nice. 👍  This PR https://github.com/atom/tabs/pull/300 would allow that.

> Seems the "minimum" setting does make the tabs wider depending on content, but it doesn't take into account that the x for closing the tab also needs to fit, and it's poorly visible when it overlaps the filename.

That's odd, I can't reproduce it. The text should fade away when the `x` is shown:

![tabs-fade](https://cloud.githubusercontent.com/assets/378023/15625054/9cf62bb0-24d4-11e6-8afd-29f674017674.gif)

Do you have a package installed that might conflict? You can try to run Atom in safe mode (only default packages) with `atom --safe`.

**Comment by adambuczynski** [comment] 2016-05-28 05:06
@simurai Yes, I've switched to "even" now which works better for me. I guess this setting must have been introduced recently, because I thought "even" was the default behaviour and that's what I got used to. Now, the default seems to be "auto", which switches to the "minimal" tabs too soon for my liking.

It's probably worth tweaking the "auto" setting just a bit more to take into account the number of open tabs as a ratio of the available space or something similar.

Thanks, I'll subscribe to that PR.

> Also, the x should only be visible when hovering the tab.

...doh. I just realised I had hacked this in my CSS to be always visible, as I prefer it like that for faster & more precies mouse movement to the `x`. I will play around with it to make it look a bit better. Sorry for that.

**Comment by simurai** [comment] 2016-06-01 07:18
> I guess this setting must have been introduced recently, because I thought "even" was the default behaviour 

Yes, sorry. "Even" used to be the default. By making "auto" the default, I was hoping people would discover that feature more easily and appreciate it. But I also agree that changing defaults shouldn't be done without a good reason, especially after Atom launched `1.0`.

**Comment by simurai** [comment] 2016-06-03 03:25
Ok, closing this. The "better use available space" is probably out of scope for the near future, but something to consider later.

**Closed by simurai** 2016-06-03 03:25 UTC
Labels: feedback

**Comment by adambuczynski** [comment] 2016-06-03 03:38
Ok, so we're leaving "auto" the default?

**Comment by simurai** [comment] 2016-06-03 03:52
Yeah, I think so. Then it's consistent with the "Font Size" and "Layout Mode" that are also set to "Auto".

![screen shot 2016-06-03 at 12 45 32 pm](https://cloud.githubusercontent.com/assets/378023/15768204/dcabd4a8-2989-11e6-8bd3-dd26eed45756.png)

**Comment by sveme** [comment] 2016-08-24 18:37
Has this feature been removed? I'm on Atom 1.9.9 and the only option I can see in Settings is Font Size - no Layout Mode, no Tab Sizing. I'm on Ubuntu 14.04 if that makes any difference, can't check it on my other computers right now.

**Comment by simurai** [comment] 2016-08-25 03:18
> @sveme Has this feature been removed?

No, Layout Mode and Tab Sizing should still be there.

Just to be sure, are you looking at Theme > Settings? Because the "Editor Settings" also have a "Font Size" option.

![screen shot 2016-08-25 at 12 14 22 pm](https://cloud.githubusercontent.com/assets/378023/17955524/de198d06-6abd-11e6-94fe-d204ea23fe20.png)

**Comment by sveme** [comment] 2016-08-25 07:40
@simurai Man, thanks and sorry, sometimes when it's late reading comprehension simply fails me.
