### ISSUE TITLE
Scrollbar color in tree view

### ISSUE THREAD

**Issue by niccolomineo** [atom/one-dark-ui#220] opened 2017-09-22 19:23 UTC
Hi, I noticed this is the scrollbar's appearance in the tree view, using a dark syntax scheme:

![schermata 2017-09-20 alle 00 42 40](https://user-images.githubusercontent.com/5409469/30618887-c0d05294-9d9c-11e7-8d3c-b9ece080c4ca.png)

Would it be possible to have it match the color and behaviour of the main editor scrollbars?

Thank you and keep up the great work,
N

**Comment by rsese** [comment] 2017-09-25 19:22
Thanks for taking the time to contribute!

We noticed that this is a duplicate of https://github.com/atom/atom/issues/15401. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2017-09-25 19:22 UTC
