### ISSUE TITLE
Long lines become invisible beyond character 1099

### ISSUE THREAD

**Issue by sirodoht** [atom/one-dark-ui#118] opened 2016-01-28 18:58 UTC
Long lines over 1099 characters become invisible beyond 1100 character. In the screenshot below I have marked until char 1103 but nothing shows up while the row:column counter on the status bar keeps increasing. This only happens with one-dark-ui and one-light-ui.

<img width="289" alt="screen shot 2016-01-28 at 8 45 08 pm" src="https://cloud.githubusercontent.com/assets/553444/12655126/26267022-c600-11e5-9af2-1a7e8f19a71e.png">

Also, as you can see in this screenshot, when the pigments package renders the characters it works OK.

<img width="255" alt="screen shot 2016-01-28 at 8 48 33 pm" src="https://cloud.githubusercontent.com/assets/553444/12655204/86fb1f4c-c600-11e5-9d71-75486548b4d8.png">

**Comment by lee-dohm** [comment] 2016-01-28 19:22
Have you followed the suggestions in the [Debugging document](https://atom.io/docs/latest/hacking-atom-debugging)? Also, could you give the following information?

* Which version of Atom are you using?
* What OS and version are you running?
* Can you reproduce the issue after completely exiting Atom and restarting using `atom --safe`?

**Comment by sirodoht** [comment] 2016-01-29 00:01
I have followed the debugging document with no luck.

I am using Atom 1.4.1 on OS X El Capitan. If I restart with `--safe` there is no problem. Also, there is no problem if I change the Atom UI theme.

**Comment by lee-dohm** [comment] 2016-01-29 00:09
If it clears up when you restart in Safe Mode, it is most likely a community package that is causing the problem.

@simurai This sounds familiar. I thought this was fixed? Do you know what might be causing it?

**Comment by sirodoht** [comment] 2016-01-29 00:21
Well, I have disabled every package and the problem seems to persist until I change to something other than One Dark or One Light UI themes.

**Comment by alexhicks** [comment] 2016-01-29 00:27
I think the fix might still be coming through the pipes.

@sirodoht Could you try the temporary fix described here https://github.com/atom/one-dark-ui/pull/112#issuecomment-163748608 just to make sure its something new.

**Comment by sirodoht** [comment] 2016-01-29 00:33
Aha! Yes, the fix works.

So, I guess I have to wait for the new Atom release.

**Comment by lee-dohm** [comment] 2016-01-29 00:36
It looks like the fix is in the v1.5.x Betas. But yes, it should come out when v1.5 reaches Stable.

**Closed** 2016-01-29 00:36 UTC
Labels: duplicate
