### ISSUE TITLE
Edited indicator not working after OSX restore

### ISSUE THREAD

**Issue by gpiffault** [atom/one-dark-ui#101] opened 2015-09-23 10:53 UTC
How to reproduce (OSX 10.10.5, Atom 1.0.15, one-dark-ui 1.0.4):

- Open a file
- When you edit the file you get the blue pill on the tab indicating the file is not saved
- Quit Atom
- Open Atom, your window and tab should be restored
- When you edit the file on the restored tab the blue pill doesn't show up (works as expected if you close and reopen the tab)

**Comment by 50Wliu** [comment] 2015-09-23 12:57
Duplicate of atom/atom#8849, please subscribe there for updates.
In addition, do you mean one-dark-ui 1.1.4?

**Closed by 50Wliu** 2015-09-23 12:57 UTC

**Comment by gpiffault** [comment] 2015-09-23 13:07
Ok, sorry for the duplicate.

However I meant one-dark-ui 1.0.4, no typo here. That's the version which shows up in my atom Settings/Themes panel. I just checked and atom says everything is up to date.

![capture d ecran 2015-09-23 a 15 06 50](https://cloud.githubusercontent.com/assets/2240251/10045654/c9c98c6a-6204-11e5-99e8-297a29191be1.png)

**Comment by 50Wliu** [comment] 2015-09-23 13:10
False alarm, sorry :see_no_evil:!
Atom 1.0.15 is still on one-dark-ui 1.0.4, but `master` is on 1.1.4 :P
