### ISSUE TITLE
close-icon is not at the proper location after configuration

### ISSUE THREAD

**Issue by windspectator** [atom/one-dark-ui#129] opened 2016-03-22 11:09 UTC
![screenshot from 2016-03-22 04-03-15](https://cloud.githubusercontent.com/assets/15637568/13949612/3aac59f0-efe3-11e5-9d12-91d2cb88fb06.png)
as what's shown in picture above, the close-icon is too close to the bottom after i modified styles.less. Or is there any configuration i can write to styles.less to fix this issue?

**Comment by thomasjo** [comment] 2016-03-22 12:36
Since this is not a bug in the theme, but rather a consequence of you altering the theme styles via your personal stylesheet (`styles.less`), I'm going to close this.

Please use [Discuss](https://discuss.atom.io/) or [Slack](https://discuss.atom.io/t/join-us-on-slack/16638) for getting help with this type of issue.

**Closed by thomasjo** 2016-03-22 12:36 UTC
