### ISSUE TITLE
Values in UI are buggy under certain conditions

### ISSUE THREAD

**Issue by nanohard** [atom/one-dark-ui#142] opened 2016-06-17 17:13 UTC
**System Info:**
OS: Arch Linux
Atom    : 1.8.0
Electron: 0.36.12
Chrome  : 47.0.2526.110
Node    : 5.1.1

**Problem:**
In Preferences > Themes > One Dark Ui > Settings > Layout Mode:
Setting it to "Auto" causes all Atom Editor UI fields to appear blank (depending on Font Size setting), or if the default text is long most characters will be missing, until that field is selected.

**Reproduction Steps:**
Go to the setting mentioned above, set Layout Mode to "Auto".
Set Font Size to 13.

**Expected behavior:**
All text input field values should be visible.

**Observed behavior:**
No text input field values are visible until selected.

**Screenshots and GIFs**
![output](https://cloud.githubusercontent.com/assets/10169206/16158768/db4f2fb6-348c-11e6-9ed8-1498bb65f6aa.gif)

**Additional information:**
- Problem can be reproduced in safe mode: Yes
- Problem started happening recently, didn't happen in an older version of Atom: Unknown
- Problem can be reliably reproduced, doesn't happen randomly: Yes
- Problem happens with all files and projects, not only some files or projects: N/A

**Comment by simurai** [comment] 2016-06-18 01:40
I can't reproduce this, but I'm on OS X. Did you try it with Atom `1.9`, currently in [Beta](https://atom.io/beta)?

**Comment by nanohard** [comment] 2016-06-18 02:16
No, I need to stay on stable. It might be that it can't render certain fonts at certain sizes, or it has something to do with my desktop theme. I'll update if I find the cause, it isn't too important.

**Comment by simurai** [comment] 2018-08-22 13:46
Closing...

Changing the Font Size without "jumping" is fixed and the Layout Mode got removed.

**Closed by simurai** 2018-08-22 13:46 UTC
Labels: needs-reproduction
