### ISSUE TITLE
After opening several, tabs are not all displayed.

### ISSUE THREAD

**Issue by valix** [atom/one-dark-ui#117] opened 2016-01-23 09:15 UTC
After opening several tabs (about 18), the tabs are not all displayed. Atom 1.5.0-beta0

![cfdf7f84-bb7c-11e5-85b9-5194fcc053b4](https://cloud.githubusercontent.com/assets/296379/12529527/2c68c448-c1ba-11e5-94ae-1c83cebd5c72.png)

**Comment by lee-dohm** [comment] 2016-01-25 01:14
This is a duplicate of https://github.com/atom/tabs/issues/136, please subscribe there for updates.

**Closed by lee-dohm** 2016-01-25 01:14 UTC
