### ISSUE TITLE
[1.2.0-beta1] When a search has many results, listings are not rendered around the halfway point.

### ISSUE THREAD

**Issue by jonboiser** [atom/one-dark-ui#109] opened 2015-11-08 00:53 UTC
<img width="490" alt="screen shot 2015-11-07 at 6 38 32 pm" src="https://cloud.githubusercontent.com/assets/10248067/11018133/4850eeb4-857f-11e5-8263-02e7f8d81d70.png">

Version 1.2.0-beta1 on OSX El Capitan. And One Dark/Light Theme. 

Does not appear to be an issue in 1.1.0. Seems to work with other themes too.

**Comment by simurai** [comment] 2015-11-08 06:01
I tested with 1000 found results, but can't reproduce it. What project is the above screenshot? Or if it's not a public repo, can you reproduce it all the time. Like let's say seraching for `module` in https://github.com/atom/atom?

**Comment by jonboiser** [comment] 2015-11-08 20:50
Weirdly, now I can't reproduce the problem. I:

1. Confirmed I was still having the problem with my work project.
2. Cloned atom and confirmed your finding that search worked fine.
3. Went back to my work project and discovered that search was working fine.

Too much has happened that I don't think I can isolate and reproduce that screenshot, so I'll close this issue for now.

**Comment by simurai** [comment] 2015-11-10 07:55
Maybe it only happens when doing a certain sequence of steps.. like opening a certain package or so. Or it's a rendering glitch that is hard to reproduce.

Feel free to reopen if it comes back.

**Comment by trevorpowell** [comment] 2015-11-17 22:14
I am seeing this too with this theme. If I use "Atom Dark" it works okay. The scrolled content with the find results disappears at some point. Oddly enough, clicking to expand or collapse a folder in the file tree view causes the scrolled content to appear.

<img width="1440" alt="screen shot 2015-11-17 at 4 09 53 pm" src="https://cloud.githubusercontent.com/assets/525402/11226462/b695ce26-8d45-11e5-883c-c4735a339342.png">

I think, related to this, the list of installed packages is cut off too.

<img width="1440" alt="screen shot 2015-11-17 at 4 13 41 pm" src="https://cloud.githubusercontent.com/assets/525402/11226544/45181686-8d46-11e5-824e-53d0ebb80847.png">

**Comment by trevorpowell** [comment] 2015-11-17 22:17
I can't reopen this, but can file a new issue if needed.

**Comment by trevorpowell** [comment] 2015-11-17 22:19
I am using Atom 1.2.1.

**Comment by simurai** [comment] 2015-11-18 00:53
@trevorpowell Ok, I'll reopen it again. Based on the second screenshot of the settings it looks like some rendering glitch. 

Does it happen randomly or can you reproduce it every time? You can also try in [safe mode](https://atom.io/docs/latest/hacking-atom-debugging#check-if-the-problem-shows-up-in-safe-mode) to see if the problem still exists. Then Atom doesn't load any community packages that might have an influence.

**Comment by trevorpowell** [comment] 2015-11-18 02:16
Thanks. I can reproduce it every time. It does occur in safe mode too. I am on OS X 10.11.1.

**Comment by toddmazierski** [comment] 2015-12-01 19:23
Hi, all! I've also been having trouble with the "One Dark" UI theme cutting off results (in my case, the file tree). If I switch to the "Atom Dark"  UI theme, the bug is no longer reproducible.

Below is a screenshot of Atom 1.2.4 on Mac OS X 10.10.5. I created a temporary project with a bunch of random files.

<img width="1437" alt="screen shot 2015-12-01 at 2 16 42 pm" src="https://cloud.githubusercontent.com/assets/544541/11511302/53633126-9836-11e5-99e8-330ba57d62eb.png">

**Please note**: I added the red border to measure the height of the cut-off point (7,875 pixels), in case that was interesting.

**Comment by simurai** [comment] 2015-12-06 05:56
I could reproduce this for the first time.. similar to @toddmazierski. When the tree-view gets pretty long, at some point it gets cut off. Once I click inside the tree-view, it shows again like normal.

<img width="593" alt="screen shot 2015-12-05 at 9 14 33 pm" src="https://cloud.githubusercontent.com/assets/378023/11611952/07eff9f6-9b9a-11e5-8c6d-eff8f348bc84.png">

Also, interesting.. Since I'm currently traveling, I use my 13" MBP with a retina screen. And it looks like all screenshots posted above are from _retina screens_.

**Comment by simurai** [comment] 2015-12-07 06:09
It might be related to the tree-view marker #112.

If somebody wants to test in your `styles.less` if removing the `transform` has an effect:

```less
.tree-view::before {
  transform: none;
}
```

**Comment by toddmazierski** [comment] 2015-12-07 15:18
Nice one, @simurai! :rocket: The [CSS change you suggested](https://github.com/atom/one-dark-ui/issues/109#issuecomment-162419438) _does_ appear to fix the bug with the file tree [I reported](https://github.com/atom/one-dark-ui/issues/109#issuecomment-161069160):

![animation of CSS being applied and unapplied](http://g.recordit.co/MWlWTUG1q7.gif)

**Comment by matttarantino** [comment] 2016-01-13 17:51
@simurai :+1: :+1: :+1: 

This bug is so annoying but glad I can get back to work now :)

**Comment by simurai** [comment] 2016-03-23 04:39
Should be fixed with https://github.com/atom/one-dark-ui/pull/112, closing.

**Closed by simurai** 2016-03-23 04:39 UTC
Labels: bug, more-information-needed, ui
