### ISSUE TITLE
editor[mini] font-size is quite large

### ISSUE THREAD

**Issue by braver** [atom/one-dark-ui#63] opened 2015-05-08 20:39 UTC
To me this feels a bit off-balance. The font-size for the mini editor, e.g. in find&replace is much larger than that of the surrounding ui (14px vs 11px in this case). A matter of taste perhaps, but I'm just putting it out there.

![screen shot 2015-05-08 at 22 34 38](https://cloud.githubusercontent.com/assets/2543659/7545076/1188e602-f5d3-11e4-93a4-cc39d7dc0f25.png)

**Comment by simurai** [comment] 2015-05-09 05:38
What font are you using? I think the problem is that the default (Inconsolata, if you have it installed) renders much smaller than the others.

![font](https://cloud.githubusercontent.com/assets/378023/7548890/fe95d7ae-f658-11e4-8afc-434be3cec703.gif)

Maybe another good reason to bundle a default font.

**Comment by braver** [comment] 2015-05-09 07:47
Oh, the default does look a lot better. I'm using Input Mono.

**Comment by jsg2021** [comment] 2015-05-11 19:32
If the theme references non-default system fonts, I would expect a shout out/warning that the font isn't available. Can Atom know that?  

+1 for bundling custom fonts.

**Comment by braver** [comment] 2015-05-11 19:57
> If the theme references non-default system fonts, I would expect a shout out/warning that the font isn't available.

Atom doesn't know the system fonts (theres an issue open for that somewhere) and I don't think Chromium can really warn you about it. The entire web is built around "just make the best of it"...

In most themes the mini-editor uses the same font as the main editor. I've always found that to be quite odd as it's part of the application UI, not of the code you're editing. The font you chose for programming might not look any good at the font-size of the UI. E.g. some bitmap fonts only look good at an exact pixel size, and Input Mono looks best (on non-Retina at least) at the 11px it was designed for.
Also, Open Sans at 12px looks huge next to Source Code Pro at 12px.
So all of that means that IMO you can't safely mix a programming font into the UI. But I'm also very picky ;)

**Comment by simurai** [comment] 2015-05-12 01:04
I think for the find+replace it makes sense to use the same font as the editor. So that the word you're trying to find looks the same. But yeah.. not sure why the mini editor is used in other places like fuzzy finder or in the settings (except for Font Family). I think there a normal `<input type="text">` would be enough. And then the font would be the same as in the UI.

**Comment by simurai** [comment] 2015-05-19 11:25
I'll close this for now. Some options for the future:

- Bundle a different default font for the editor.
- Replace the mini editors with normal `<input type=text>`
- Maybe try to override the font for mini editors.

**Comment by simurai** [comment] 2015-06-15 08:45
If https://github.com/atom/atom/pull/7281 gets merged, this issue would be open again.

**Closed** 2015-06-20 07:08 UTC
Labels: blocked
