### ISSUE TITLE
Tabs: Bad text rendering during hoover transition

### ISSUE THREAD

**Issue by vegar** [atom/one-dark-ui#27] opened 2015-03-27 20:51 UTC
When hoovering over the file tabs, there's a .1s transition showing the x to close the tab.

During this short time, the text in the tab 'shakes' a little, but enough to freak me out...

I've solved it locally by adding the following to my stylesheet:

```js
.theme-one-dark-ui {
  .tab-bar {
    .tab {
      .close-icon {
        transition: transform .0s;
      }
    }
  }
}
```

Is there a way of keeping the transition without affecting the text rendering?

**Comment by braver** [comment] 2015-03-27 21:41
Hm, that's weird, I never got that. But I'm working on a big refactor that I'll release this weekend, perhaps that will also be fixed then.

**Comment by vegar** [comment] 2015-03-27 21:59
I see the problem on both my computers.

BUT after testing some more, the problem is only there if the tree view is
visible. That's kind of strange, isn't it?

2015-03-27 22:41 GMT+01:00 Koen Lageveen <notifications@github.com>:

**Comment by braver** [comment] 2015-03-27 22:11
yes, it is that.

**Comment by simurai** [comment] 2015-03-28 07:07
I can't reproduce it here, but I've seen this happen in Chrome/Chromium sometimes. Somehow related to  using transforms and rendered on the GPU.

Something that helped in the past is adding:

```css
backface-visibility: hidden;
```

You'd have to try it out where to add it.. maybe to the `.title`?

**Comment by vegar** [comment] 2015-03-28 20:07
Great! Adding it to the either .tab or .title both solves the issue for me:

```css
.theme-one-dark-ui {
   .tab-bar {
      .tab {
          .title {
              backface-visibility: hidden;
          }
      }
  }
}
```

**Comment by vegar** [comment] 2015-03-31 22:27
Since you are reopening it as a bug...

It seems to affect more than just the tabs. All the text in the settings view also do the happy dance during transformations.

**Comment by simurai** [comment] 2015-03-31 22:33
@vegar Yes, since there is another issue https://github.com/atom/atom/issues/6183 I figured it's better to try to fix it in the theme. I still can't reproduce it, but I'll try to change the tabs to not use `opacity`. That might conflict with the close icon `transform`.

**Comment by mnpenner** [comment] 2015-04-01 01:19
The `backface-visibility` fix that @vegar posted seems to fix the tabs for me, but not the settings.

![](http://i.imgur.com/B8wZAvc.gif)

**Comment by simurai** [comment] 2015-04-03 00:47
The tab background is now an own layer. Not sure if it actually fixes this issue, but we'll see in the next update.

**Comment by simurai** [comment] 2015-04-14 07:42
@vegar @mnpenner Do you still see it after updating to Atom `0.191.0`?

**Comment by vegar** [comment] 2015-04-14 08:22
I have 0.190.0 which atom claims to be the latest version.

But the problem is gone as far as I can see. I'll have a look on my other computer as well later to day.

(@mnpenner : What software did you use for the screenshots? I was looking for something like that when I first created the issue.)

**Comment by mnpenner** [comment] 2015-04-14 15:33
@vegar [ShareX](https://getsharex.com/). Great program, but unfortunately Windows only.

@simurai Will check when I get home.

**Comment by mnquintana** [comment] 2015-04-14 15:51
(@vegar You can also check out [LICEcap](http://www.cockos.com/licecap/), which is free, for Windows and OS X, and is what a lot of us use)

**Comment by vegar** [comment] 2015-04-14 20:13
ok, Checked on second pc as well. Can confirm what you say, @simurai , the problem is somewhat better. It only wiggle when activating a tab. The `backface-visibility` fix from earlier seems to fix this wiggle.

(Thanks for good software tips. Trying ShareX out. Looks a little complex, but good never the less.)

**Comment by simurai** [comment] 2015-04-15 06:44
Thanks for checking.. let's keep it open if there is still wiggling when activating. There might be some more tab changes coming.

**Comment by mnpenner** [comment] 2015-04-16 05:31
Running 0.192.0 now.

![](http://i.imgur.com/p41ZLqA.gif)

The settings tab doesn't shuffle around anymore, but the tabs still do.

**Comment by simurai** [comment] 2015-07-29 06:24
There was a [recent change](https://github.com/atom/one-dark-ui/commit/223743885172cf8ae697f309023ff2c2dfa10a57) in the implementation of the tabs.

Can anyone still reproduce this issue with Atom `1.0.3`?

**Comment by simurai** [comment] 2016-06-03 03:27
Closing this. Feel free to open a new issue if things haven't improved.

**Closed by simurai** 2016-06-03 03:27 UTC
Labels: bug, needs-testing
