### ISSUE TITLE
Unable to select file above selected file in Tree View

### ISSUE THREAD

**Issue by keithjgrant** [atom/one-dark-ui#265] opened 2018-06-11 15:06 UTC
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

While a file is open and active/selected, I am unable to click the file directly above it in the tree view.

### Steps to Reproduce

1. Enable sticky headers option in plugin settings
2. Open a file
3. In the tree view, click on the file directly above the currently opened file

**Expected behavior:** The clicked file should open

**Actual behavior:** File does not open

**Reproduces how often:** 100%

### Versions

one-dark-ui 1.12.1

Atom    : 1.27.2
Electron: 1.7.15
Chrome  : 58.0.3029.110
Node    : 7.9.0

OS X 10.11.6

### Additional Information

This is caused by the top padding and negative top margin on the selected item in the Tree View. The top padding covers the element above, making it un-clickable

![screen shot 2018-06-11 at 11 04 53 am](https://user-images.githubusercontent.com/410794/41239986-6e7dfb54-6d67-11e8-8678-b151b2e11df4.png)

![screen shot 2018-06-11 at 11 05 13 am](https://user-images.githubusercontent.com/410794/41239972-698d2f7a-6d67-11e8-91fa-e981753ae054.png)
 (screenshots attached)

**Comment by rsese** [comment] 2018-06-11 17:21
Thanks for contributing!

This is a duplicate of https://github.com/atom/one-dark-ui/issues/257 which is [fixed](https://github.com/atom/one-light-ui/pull/133) as of 1.28 (currently in beta).

---

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

https://github.com/atom/one-light-ui/pull/133

**Closed by rsese** 2018-06-11 17:21 UTC
