### ISSUE TITLE
Default theme "one dark"

### ISSUE THREAD

**Issue by Feichtmeier** [atom/one-dark-ui#267] opened 2018-07-07 06:03 UTC
### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

The one dark theme has some big squares between each block:
![screenshot from 2018-07-07 08-00-23](https://user-images.githubusercontent.com/15329494/42407400-2258d76c-81bc-11e8-9366-f5a37763be64.png)

### Steps to Reproduce

Install atom and open any file

**Comment by Arcanemagus** [comment] 2018-07-07 08:11
Thanks for taking the time to contribute!

We noticed that this is a duplicate of https://github.com/atom/one-dark-ui/issues/266. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by Arcanemagus** 2018-07-07 08:11 UTC
