### ISSUE TITLE
sometimes the scroll become white (I use one dark)

### ISSUE THREAD

**Issue by max210** [atom/one-dark-ui#235] opened 2018-01-12 07:27 UTC
### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

[Description of the issue]

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expect to happen]

**Actual behavior:** [What actually happens]

**Reproduces how often:** [What percentage of the time does it reproduce?]

### Versions

You can get this information from copy and pasting the output of `atom --version` and `apm --version` from the command line. Also, please include the OS and what version of the OS you're running.

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by max210** [comment] 2018-01-12 07:28
<img width="1096" alt="2018-01-12 15 26 57" src="https://user-images.githubusercontent.com/27328565/34864006-2de86a78-f7ad-11e7-9e84-01615c2c41fc.png">

**Comment by max210** [comment] 2018-01-12 07:30
<img width="1096" alt="2018-01-12 15 26 57" src="https://user-images.githubusercontent.com/27328565/34864061-73c7ad06-f7ad-11e7-885a-3caf2118c0eb.png">

**Comment by max210** [comment] 2018-01-12 07:30
<img width="1096" alt="2018-01-12 15 26 57" src="https://user-images.githubusercontent.com/27328565/34864061-73c7ad06-f7ad-11e7-885a-3caf2118c0eb.png">

**Comment by rsese** [comment] 2018-01-12 19:37
Thanks for taking the time to contribute!

Based on just the screenshot, I think this is probably a duplicate of https://github.com/atom/atom/issues/15350. You can subscribe there for updates if you'd like.

For future issues, please fill out the issue template, it's really helpful for us when investigating issues.

---

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2018-01-12 19:37 UTC

**Comment by max210** [comment] 2018-01-15 02:20
think you！
