### ISSUE TITLE
No more spacious layout mode?

### ISSUE THREAD

**Issue by JesseLeite** [atom/one-dark-ui#209] opened 2017-05-17 17:35 UTC
I see `layoutMode` was deprecated 😢  Is there any way to get spacious tabs back?

![](http://b3.ms/06j9do8vMabK)

**Comment by geoffb** [comment] 2017-05-17 18:08
I know it may seem like a small thing to some users, but the spacious tab size was one of the main reasons I chose to use One Dark. Please consider that users choose your theme for a reason before making significant changes.

**Comment by JesseLeite** [comment] 2017-05-17 18:51
100%.  I loved the coloured left border on the active tab as well.  Those that wanted compact tabs could opt out of spacious.  Sad to see this go 😭

**Comment by mmcbride1007** [comment] 2017-05-17 20:44
this is a dupe of #198

**Comment by rsese** [comment] 2017-05-17 22:32
Thanks @mmcbride1007, closing as a dupe of #198.

**Closed by rsese** 2017-05-17 22:32 UTC
